Authentication
t-bello7/micro-blog pull request #11
Opened 2022-12-16 02:21 UTC by t-bello7

I implemented the following functionalities :
- Users can register 
- User logs in with a combination of email and password.
- Hashed password should be stored in the database.
- Ask for confirmation by email.
- User can reset password

2022-12-16 02:54 UTC, Davidosky007 requested changes
Hi @t-bello7 @GordonOtieno 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* No linter errors 👍 
* Proper use of Gitflow 👍 
* Well written PR description 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 02:54 UTC, Davidosky007 commented on app/controllers/application_controller.rb
> +  # end
* Kindly remove all commented code as it makes your code base bulky and unprofessional 🙏

2022-12-16 02:54 UTC, Davidosky007 commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
* Kindly ensure your devise setup Asks for confirmation of email during signup as stated in [the requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/blog_app_devise.md#:~:text=Ask%20for%20confirmation%20of%20email.) 
* Also when i try to reset my password i get this error `Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true`, Kindly fix this error [Following this devise setup instructions helped fix this error](https://github.com/heartcombo/devise#:~:text=config.action_mailer.default_url_options%20%3D%20%7B%20host%3A%20%27localhost%27%2C%20port%3A%203000%20%7D)
![image](https://user-images.githubusercontent.com/52497246/208011258-75506b78-21e7-4e92-a7f4-245833a0b2d4.png)

2022-12-16 09:07 UTC, prolajumokeoni requested changes
Hi @t-bello7 and @GordonOtieno 
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used  

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Kindly ensure that as partners you always have balanced commits in a pair programming project 👍 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-16 09:07 UTC, prolajumokeoni commented on app/models/user.rb
> +         :recoverable, :rememberable, :validatable
- [ ]  Based on the requirements of this project, this app should ask for email confirmation please enable  `:confirmable`  in your user.rb
- Just as the previous reviewer requested, please  ensure  your  application asks for confirmation of email, currently I can signin without confirming my email

2022-12-16 15:32 UTC, merged

2022-12-19 15:49 UTC, GzimAsani reviewed
# STATUS: APPROVED :100:         
## There is nothing else to say than it's time to merge... :partying_face: 
Cheers and Happy coding! :clap:  :computer:  :wine_glass: 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


## Optional suggestions


_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
### Please be reminded to not open a new pull request after you get a review, only use the same one :thought_balloon: 


 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

### PS: I think I forgot to hit submit the review when I approved your project. I am glad you figured it out :joy: